title: "Elvira Gouatieu Dongmo"
logo: image/elvi.jpg
description: "Portfolio Computational Scientist"
show_downloads: true
#theme: jekyll-theme-minimal
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
url: "https://elviradongmo.github.io"
baseurl: "/portfolio"
lang: en
