title: "Elvira Gouatieu Dongmo"
name: "Elvira Gouatieu Dongmo"
description: "Computational Scientist | Applied Mathematician | AI for Scientific Discovery"
show_downloads: true
url: "https://elvira123-hub.github.io"
baseurl: "/elvira.dongmo"
theme: jekyll-theme-minimal
#remote_theme: "mmistakes/minimal-mistakes"

#plugins:
  #- jekyll-remote-theme
  #- jekyll-include-cache

minimal_mistakes_skin: "default"
locale: "en-US"
logo: image/elvi.jpg
#logo: "/assets/images/elvi.jpg"



